name: build-release
run-name: Release for commit ${{ github.sha }}
on: push
jobs:
  build:
    runs-on: ubuntu-22.04 # ubuntu-latest?
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get install build-essential
      - run: make OUTPUT=containd-$${{ github.sha }}-x86_64
        
      - uses: softprops/action-gh-release@v1
      with: 
        name: release-$${{ github.sha }}
        body: release for commit $${{ github.sha }}
        files: containd-$${{ github.sha }}